{
 "title": "iDRAC Telemetry Streaming",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "iDRAC_Host", "label": "iDRAC Host", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "System Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PowerEdge_SystemUsage_CPUUsage{instance=\"$iDRAC_Host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PowerEdge_SystemUsage_MemoryUsage{instance=\"$iDRAC_Host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sensor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "System Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "PowerEdge_PowerMetrics_SystemPowerConsumption{instance=\"$iDRAC_Host\"}",
     "legendFormat": "{{FQDD}}"
    }
   ]
  },
  {
   "title": "Voltage Reading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "PowerEdge_Sensor_VoltageReading{instance=\"$iDRAC_Host\"}",
     "legendFormat": "{{FQDD}}"
    }
   ]
  },
  {
   "title": "Fan RPM Speed",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "PowerEdge_PSUMetrics_PSUTemperatureReading{instance=\"$iDRAC_Host\"}",
     "legendFormat": "{{FQDD}}"
    },
    {
     "expr": "PowerEdge_Sensor_RPMReading{instance=\"$iDRAC_Host\"}",
     "legendFormat": "{{FQDD}}"
    }
   ]
  },
  {
   "title": "Temperature Reading",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "PowerEdge_PSURPMReading{instance=\"$iDRAC_Host\"}",
     "legendFormat": "{{FQDD}}"
    },
    {
     "expr": "PowerEdge_MemorySensor_TemperatureReading{instance=\"$iDRAC_Host\"}",
     "legendFormat": "{{FQDD}}"
    }
   ]
  },
  { "title": "Memory Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Temperature Threshold Alarm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "PowerEdge_MemoryMetrics_TemperatureThresholdAlarm{instance=\"$iDRAC_Host\"}",
     "legendFormat": "{{FQDD}}"
    }
   ]
  },
  {
   "title": "Address Parity Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "PowerEdge_MemoryMetrics_AddressParityError{instance=\"$iDRAC_Host\"}",
     "legendFormat": "{{FQDD}}"
    }
   ]
  },
  {
   "title": "Uncorrectable ECC Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "PowerEdge_MemoryMetrics_UncorrectableECCError{instance=\"$iDRAC_Host\"}",
     "legendFormat": "{{FQDD}}"
    }
   ]
  },
  {
   "title": "Correctable ECC Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "PowerEdge_MemoryMetrics_CorrectableECCError{instance=\"$iDRAC_Host\"}",
     "legendFormat": "{{FQDD}}"
    }
   ]
  },
  {
   "title": "Watts Reading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "PowerEdge_Sensor_WattsReading{instance=\"$iDRAC_Host\"}",
     "legendFormat": "{{Metric}}"
    }
   ]
  },
  { "title": "Storage Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "CRC Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "PowerEdge_StorageDiskSMARTData_CRCErrorCount{instance=\"$iDRAC_Host\"}",
     "legendFormat": "{{FQDD}}"
    }
   ]
  },
  {
   "title": "Uncorrectable Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "PowerEdge_StorageDiskSMARTData_UncorrectableErrorCount{instance=\"$iDRAC_Host\"}",
     "legendFormat": "{{FQDD}}"
    }
   ]
  },
  {
   "title": "Uncorrectable LBA Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "PowerEdge_StorageDiskSMARTData_UncorrectableLBACount{instance=\"$iDRAC_Host\"}",
     "legendFormat": "{{FQDD}}"
    }
   ]
  },
  {
   "title": "Read Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "PowerEdge_StorageDiskSMARTData_ReadErrorRate{instance=\"$iDRAC_Host\"}",
     "legendFormat": "{{FQDD}}"
    }
   ]
  },
  {
   "title": "Uncorrectable LBA Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "PowerEdge_StorageDiskSMARTData_ProgramFailCount{instance=\"$iDRAC_Host\"}",
     "legendFormat": "{{FQDD}}"
    }
   ]
  },
  {
   "title": "Percentage Life Remaining",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "PowerEdge_StorageDiskSMARTData_PercentDriveLifeRemaining{instance=\"$iDRAC_Host\"}",
     "legendFormat": "{{FQDD}}"
    }
   ]
  },
  { "title": "Network/FC Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Discarded Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "PowerEdge_NICStatistics_DiscardedPkts{instance=\"$iDRAC_Host\"}",
     "legendFormat": "{{FQDD}}"
    }
   ]
  },
  {
   "title": "Receive Packet Alignment Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "targets": [
    {
     "expr": "PowerEdge_NICStatistics_RxErrorPktAlignmentErrors{instance=\"$iDRAC_Host\"}",
     "legendFormat": "{{FQDD}}"
    }
   ]
  }
 ]
}